server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assistants?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.tool.schema: DEBUG
